# Generated by Django 4.1.5 on 2023-02-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20, null=True)),
                ('rating', models.FloatField(default=0)),
                ('average_result', models.FloatField(default=0)),
                ('number_of_passes', models.IntegerField(default=0)),
                ('time_control', models.IntegerField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(default='', to='tests.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Test_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('test', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(null=True)),
                ('image_content', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('correctness', models.BooleanField(default=False)),
                ('question', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.questions')),
            ],
        ),
    ]
