# Generated by Django 4.1.5 on 2023-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_questions_number_alter_questions_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(),
        ),
    ]
