# Generated by Django 4.1.5 on 2023-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='question_result',
            field=models.ManyToManyField(through='tests.Question_results', to='tests.questions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='test_result',
            field=models.ManyToManyField(through='tests.Test_results', to='tests.tests'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
