# Generated by Django 4.1.5 on 2023-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='photos/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
