# Generated by Django 4.1.5 on 2023-02-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tests_password_tests_private_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
