# Generated by Django 4.1.5 on 2023-02-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tests_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='categorys',
            new_name='categories',
        ),
    ]
