# Generated by Django 4.1.5 on 2023-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(default='0', null=True),
        ),
    ]
