# Generated by Django 4.1.5 on 2023-02-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_questions_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='image_content',
        ),
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.questions'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='text_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.tests'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='categories',
            field=models.ManyToManyField(to='tests.categories'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='time_control',
            field=models.IntegerField(),
        ),
    ]
